import React from 'react';
import { useNavigate } from 'react-router-dom';

import { Content, Heading, Link } from '@adobe/react-spectrum';

function Home() {

    const navigate = useNavigate();

    return (
        <Content width="calc(100% - size-1000)">
            <Heading level={3}>A UX for dellctl!</Heading>
            <p>
                This app is... generated by an AI...
            </p>
            <p>
                <i>
                    This app provides a streamlined user interface for dellctl, the CLI tool used to manage Dell Container Storage Modules (CSM), 
                    organizing its functions into logical groups to simplify complex workflows. By grouping related commands—such as cluster management 
                    (add, remove, get), backup/restore operations, and scheduling tasks—the UI enables users to chain common sequences (e.g., creating 
                    a backup and immediately scheduling its automation) through intuitive workflows, reducing manual command-line input while maintaining 
                    compatibility with dellctl’s core functionality</i>
            </p>
            <p>
                (Seriously, that paragraph above is from an LLM...)
            </p>
            <Heading level={3}>Good Luck!</Heading>
        </Content>
    )
}


export default Home;